import { getStore } from '@netlify/blobs';
import { pbkdf2Sync, randomBytes, timingSafeEqual } from 'node:crypto';

const store=getStore('loyiha-akademiyasi');
const now=()=>Date.now();
const json=(value,status=200,headers={})=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const read=async(key,fallback)=>{const value=await store.get(key);return value?JSON.parse(value):fallback};
const write=(key,value)=>store.set(key,JSON.stringify(value));
const hash=(password,salt)=>pbkdf2Sync(password,salt,120000,32,'sha256').toString('hex');
const cookie=(request)=>Object.fromEntries((request.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
const session=async(req)=>{const token=cookie(req).loyiha_session;if(!token)return null;const sessions=await read('sessions',[]);const s=sessions.find(x=>x.token===token&&x.expires>now());if(!s)return null;const users=await read('users',[]);return users.find(x=>x.id===s.userId)||null};
const publicUser=u=>u&&({id:u.id,name:u.name,email:u.email,role:u.role});
async function body(req){try{return await req.json()}catch{fail('So‘rov ma’lumotini o‘qib bo‘lmadi.')}}
async function requireUser(req,teacher=false){const u=await session(req);if(!u)fail('Avval hisobingizga kiring.',401);if(teacher&&u.role!=='teacher')fail('Bu amal faqat o‘qituvchi uchun.',403);return u}
function safeText(v,min,max,label){if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(`${label}: ${min}–${max} belgi bo‘lishi kerak.`);return v.trim()}
async function start(req,user){const token=randomBytes(32).toString('hex'),sessions=await read('sessions',[]);sessions.push({token,userId:user.id,expires:now()+7*86400000});await write('sessions',sessions.filter(x=>x.expires>now()).slice(-3000));return json({user:publicUser(user)},200,{'set-cookie':`loyiha_session=${token}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=604800`})}

export default async (req)=>{try{const url=new URL(req.url),action=url.searchParams.get('action')||'me';
 if(action==='me'&&req.method==='GET'){const users=await read('users',[]);return json({user:publicUser(await session(req)),setupNeeded:!users.some(u=>u.role==='teacher')})}
 if(action==='auth'&&req.method==='POST'){const b=await body(req),mode=b.mode,email=safeText(b.email,5,254,'Email').toLowerCase(),password=safeText(b.password,10,128,'Parol');let users=await read('users',[]);
  if(mode==='login'){const u=users.find(x=>x.email===email);if(!u||!timingSafeEqual(Buffer.from(hash(password,u.salt),'hex'),Buffer.from(u.password,'hex')))fail('Email yoki parol noto‘g‘ri.',401);return start(req,u)}
  if(!['register','setup'].includes(mode))fail('Hisob turi noto‘g‘ri.');if(users.some(u=>u.email===email))fail('Bu email allaqachon ro‘yxatdan o‘tgan.',409);const hasTeacher=users.some(u=>u.role==='teacher');if(mode==='setup'){if(hasTeacher)fail('O‘qituvchi hisobi yaratilgan.',409);if(process.env.TEACHER_SETUP_KEY&&b.setupKey!==process.env.TEACHER_SETUP_KEY)fail('O‘qituvchi sozlash kaliti noto‘g‘ri.',403)}else if(!hasTeacher)fail('Avval o‘qituvchi hisobini sozlang.',409);
  const salt=randomBytes(16).toString('hex'),u={id:randomBytes(16).toString('hex'),name:safeText(b.name,2,100,'Ism-familiya'),email,password:hash(password,salt),salt,role:mode==='setup'?'teacher':'student',created:now()};users.push(u);await write('users',users);return start(req,u)}
 if(action==='logout'&&req.method==='POST'){const token=cookie(req).loyiha_session,sessions=await read('sessions',[]);await write('sessions',sessions.filter(x=>x.token!==token));return json({ok:true},200,{'set-cookie':'loyiha_session=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0'})}
 if(action==='submit'&&req.method==='POST'){const u=await requireUser(req),b=await body(req);const topic=Number(b.topic);if(!Number.isInteger(topic)||topic<1||topic>11)fail('Mavzu noto‘g‘ri.');const submissions=await read('submissions',[]);const row={id:randomBytes(16).toString('hex'),userId:u.id,topic,kind:safeText(b.kind,2,40,'Mashq turi'),assignment:safeText(b.assignment||`M${topic}`,2,100,'Topshiriq'),answer:b.answer,score:Number.isFinite(b.score)?b.score:null,total:Number.isFinite(b.total)?b.total:null,grade:null,feedback:b.feedback||'',reviewed:false,created:now()};submissions.push(row);await write('submissions',submissions);return json({ok:true,row})}
 if(action==='results'&&req.method==='GET'){const u=await requireUser(req);const rows=(await read('submissions',[])).filter(x=>x.userId===u.id).sort((a,b)=>b.created-a.created);return json(rows)}
 if(action==='teacher'&&req.method==='GET'){await requireUser(req,true);const users=await read('users',[]),submissions=await read('submissions',[]),contents=await read('contents',[]);return json({users:users.map(publicUser),submissions:submissions.map(s=>({...s,user:publicUser(users.find(u=>u.id===s.userId))})),contents})}
 if(action==='grade'&&req.method==='POST'){await requireUser(req,true);const b=await body(req),grade=Number(b.grade);if(![2,3,4,5].includes(grade))fail('2–5 bahoni tanlang.');const rows=await read('submissions',[]),row=rows.find(x=>x.id===b.id);if(!row)fail('Javob topilmadi.',404);row.grade=grade;row.feedback=safeText(b.feedback,3,3000,'Izoh');row.reviewed=true;await write('submissions',rows);return json({ok:true})}
 if(action==='content'&&req.method==='POST'){await requireUser(req,true);const b=await body(req),topic=Number(b.topic);if(!Number.isInteger(topic)||topic<1||topic>11)fail('Mavzu noto‘g‘ri.');const contents=await read('contents',[]);contents.push({id:randomBytes(12).toString('hex'),topic,title:safeText(b.title,3,160,'Sarlavha'),kind:b.kind==='assignment'?'assignment':'note',body:safeText(b.body,3,20000,'Mazmun'),created:now()});await write('contents',contents);return json({ok:true})}
 if(action==='upload'&&req.method==='POST'){await requireUser(req,true);const form=await req.formData(),file=form.get('file'),topic=Number(form.get('topic'));if(!(file instanceof File)||file.size<1||file.size>3*1024*1024)fail('Netlify versiyasida fayl 3 MB dan oshmasin.',413);if(!Number.isInteger(topic)||topic<1||topic>11)fail('Mavzu noto‘g‘ri.');const bytes=Buffer.from(await file.arrayBuffer()).toString('base64'),contents=await read('contents',[]);contents.push({id:randomBytes(12).toString('hex'),topic,title:safeText(String(form.get('title')||file.name),3,160,'Sarlavha'),kind:'file',filename:file.name,mime:file.type||'application/octet-stream',data:bytes,created:now()});await write('contents',contents);return json({ok:true})}
 if(action==='file'&&req.method==='GET'){await requireUser(req);const item=(await read('contents',[])).find(x=>x.id===url.searchParams.get('id')&&x.kind==='file');if(!item)fail('Fayl topilmadi.',404);return new Response(Buffer.from(item.data,'base64'),{headers:{'content-type':item.mime,'content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(item.filename)}`}})}
 fail('Amal topilmadi.',404)
}catch(e){return json({error:e.message||'Server xatosi.'},e.status||500)}};
export const config={path:'/api/*'};
